#!/bin/bash
#
# Job name:
#SBATCH --job-name=Testing_emcee_Fitting_100000
#
# Account:
#SBATCH --account=co_dweisz
#
# Partition:
#SBATCH --partition=savio2
#
# QoS:
#SBATCH --qos=dweisz_savio2_normal
#
# Wall clock limit:
#SBATCH --time=48:00:00
#
#SBATCH --output=Testing_emcee_Fitting_100000.txt
#
# Email upon completion:
#SBATCH --mail-type=END
#SBATCH --mail-user=nathan_sandford@berkeley.edu
#
## Commands to run:

module add python
python $HOME/D-Payne/development/Testing_emcee_Fitting_100000.py
