#!/bin/bash
#
# Job name:
#SBATCH --job-name=convolve_spectra
#
# Account:
#SBATCH --account=co_dweisz
#
# Partition:
#SBATCH --partition=savio_bigmem
#
# QoS:
#SBATCH --qos=low_prio
#
# Wall clock limit:
#SBATCH --time=0:05:00
#
#SBATCH --output=convolve_spectra_1.txt
#
# Email upon completion:
#SBATCH --mail-type=ALL
#SBATCH --mail-user=nathan_sandford@berkeley.edu
#
## Commands to run:

module add python
python $HOME/D-Payne/convolve_highrez_spectra_to_given_R.py
