#!/bin/bash
#
# Job name:
#SBATCH --job-name=convolve_masking_spectra
#
# Account:
#SBATCH --account=co_dweisz
#
# Partition:
#SBATCH --partition=savio2
#
# QoS:
#SBATCH --qos=dweisz_savio2_normal
#
# Wall clock limit:
#SBATCH --time=00:30:00
#
#SBATCH --output=convolve_masking_spectra.txt
#
# Email upon completion:
#SBATCH --mail-user=nathan_sandford@berkeley.edu
#
## Commands to run:

module add python
python $HOME/D-Payne/convolve_masking_spectra.py
