#!/bin/bash
#
# Job name:
#SBATCH --job-name=D-train_NN_40-49
#
# Account:
#SBATCH --account=co_dweisz
#
# Partition:
#SBATCH --partition=savio2
#
# QoS:
#SBATCH --qos=dweisz_savio2_normal
#
# Wall clock limit:
#SBATCH --time=05:00:00
#
#SBATCH --output=D-train_NN_40-49.txt
#
# Email upon completion:
#SBATCH --mail-type=END
#SBATCH --mail-user=nathan_sandford@berkeley.edu
#
## Commands to run:

module add python
python $HOME/D-Payne/train_NNs/D-train_NN.py 40 49
