#!/bin/bash
#
# Job name:
#SBATCH --job-name=emcee_autocorr
#
# Account:
#SBATCH --account=co_dweisz
#
# Partition:
#SBATCH --partition=savio2
#
# QoS:
#SBATCH --qos=dweisz_savio2_normal
#
# Wall clock limit:
#SBATCH --time=72:00:00
#
#SBATCH --output=emcee_autocorr.txt
#
# Email upon completion:
#SBATCH --mail-type=END
#SBATCH --mail-user=nathan_sandford@berkeley.edu
#
## Commands to run:

module add python
python $HOME/D-Payne/development/emcee/emcee_autocorr.py 1000
